# https://github.com/pypa/hatch/blob/master/ruff_defaults.toml
extend = "ruff_defaults.toml"

# https://github.com/astral-sh/ruff/issues/8627
exclude = [".git", ".mypy_cache", ".ruff_cache", ".venv", ".direnv",
    ".bzr",
    ".direnv",
    ".eggs",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

target-version = "py311"

[format]
preview = true

[lint]
preview = true

# Documentation and ensure that the defaults are included
extend-select = ["D", "E4", "E7", "E9", "F", "C901"]

[lint.pydocstyle]
convention = "numpy"

[lint.per-file-ignores]
'modelscripts/**/*.py' = [
    'INP001',  # Missing return type annotation for public function
]
"tests/**/test_*.py" = [
    "S101", # asserts allowed in tests
]
"**/*.ipynb" = [
    "B018", # allow notebooks printing out variables in the mid cell with variable names only
]