name: Format notebooks

on:
  workflow_call:
    inputs:
      project-folder:
        required: true
        type: string

jobs:
    test-format:
      runs-on: ubuntu-latest
      concurrency:
        # Cancel any previous runs with the same workflow name and branch
        group: ${{ inputs.project-folder }}-${{ github.workflow }}-${{ github.ref }}
        cancel-in-progress: true
      strategy:
        fail-fast: false
      env:
        HATCH_VERBOSE: 1
      steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Install hatch
        run: uv tool install hatch
      - name: Check the format of modelscripts with ruff and a minimal selection of rules
        run: hatch run lintformat:ruff check modelscripts/${{ inputs.project-folder }} --config "lint.select=['E4', 'E7', 'E9', 'F']"