name: Test notebooks

on:
  workflow_call:
    inputs:
      project-folder:
        description: 'The name of the project folder'
        required: true
        type: string
      runs-on:
        description: 'The label or group of the runner to use'
        required: false
        type: string
        default: ubuntu-latest

jobs:
    test-notebooks:
      runs-on: ${{ inputs.runs-on }}
      concurrency:
        # Cancel any previous runs with the same workflow name and branch
        group: ${{ inputs.project-folder }}-${{ github.workflow }}-${{ github.ref }}
        cancel-in-progress: true
      strategy:
        fail-fast: false
      env:
        HATCH_VERBOSE: 1
      steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Install hatch
        run: uv tool install hatch
      - name: Test notebooks in ${{ inputs.project-folder }} env
        run: hatch run ${{ inputs.project-folder }}:test